/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_web_statistics_Statistics */

#ifndef _Included_com_web_statistics_Statistics
#define _Included_com_web_statistics_Statistics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_web_statistics_Statistics
 * Method:    getStats
 * Signature: ()Lcom/web/statisticsmodel/StatisticsModel;
 */
JNIEXPORT jobject JNICALL Java_com_web_statistics_Statistics_getStats
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
